Delegate external encoding io
Not sure if this was something that was added in a new version of
minitest but I was getting this error when running tests:

```
/Users/tony/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/minitest-5.4.3/lib/minitest.rb:572:in `aggregated_results': undefined method `external_encoding' for #<Minitest::RedGreen::Plugin:0x007fd44408aff0> (NoMethodError)
        from /Users/tony/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/minitest-5.4.3/lib/minitest.rb:554:in `report'
        from /Users/tony/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/minitest-5.4.3/lib/minitest.rb:626:in `each'
        from /Users/tony/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/minitest-5.4.3/lib/minitest.rb:626:in `report'
        from /Users/tony/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/minitest-5.4.3/lib/minitest.rb:129:in `run'
        from bin/test_runner:13:in `<main>'
```

Looking at minitest it seemed to be wanting to sending that message to io so I just delegated it over and things work now.